import React from 'react'

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS'
export const LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR'
export const LOAD_PRODUCTS_PENDING = 'LOAD_PRODUCTS_PENDING'


export const LOAD_THEME_SUCCESS = 'LOAD_THEME_SUCCESS'
export const LOAD_THEME_ERROR = 'LOAD_THEME_ERROR'
export const LOAD_THEME_PENDING = 'LOAD_THEME_PENDING'
export const SET_THEME_SUCCESS = 'SET_THEME_SUCCESS'
export const SET_THEME_ERROR = 'SET_THEME_ERROR'
export const SET_THEME_PENDING = 'SET_THEME_PENDING'
