import React from 'react'

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS'
export const LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR'
export const LOAD_PRODUCTS_PENDING = 'LOAD_PRODUCTS_PENDING'
