export const productActions = {
    GET_PRODUCTS_PENDING: "GET_PRODUCTS_PENDING",
    GET_PRODUCTS_ERROR: "GET_PRODUCTS_ERROR",
    GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
    GET_PRODUCT_PENDING: "GET_PRODUCT_PENDING",
    GET_PRODUCT_ERROR: "GET_PRODUCT_ERROR",
    GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS"
};

export const userActions = {
    GET_CURRENT_USER_PENDING: "GET_CURRENT_USER_PENDING",
    GET_CURRENT_USER_ERROR: "GET_CURRENT_USER_ERROR",
    GET_CURRENT_USER_SUCCESS: "GET_CURRENT_USER_SUCCESS",
    POST_LOGIN_USER_PENDING: "POST_LOGIN_USER_PENDING",
    POST_LOGIN_USER_ERROR: "POST_LOGIN_USER_ERROR",
    POST_LOGIN_USER_SUCCESS: "POST_LOGIN_USER_SUCCESS",
    GET_LOGOUT_USER_PENDING: "GET_LOGOUT_USER_PENDING",
    GET_LOGOUT_USER_ERROR: "GET_LOGOUT_USER_ERROR",
    GET_LOGOUT_USER_SUCCESS: "GET_LOGOUT_USER_SUCCESS"
};
