export const productActions = {
    GET_PRODUCT_PENDING: "GET_PRODUCT_PENDING",
    GET_PRODUCT_ERROR: "GET_PRODUCT_ERROR",
    GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS"
};

export const productsActions = {
    GET_PRODUCTS_PENDING: "GET_PRODUCTS_PENDING",
    GET_PRODUCTS_ERROR: "GET_PRODUCTS_ERROR",
    GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS"
};

export const userActions = {
    POST_LOGIN_USER_PENDING: "POST_LOGIN_USER_PENDING",
    POST_LOGIN_USER_ERROR: "POST_LOGIN_USER_ERROR",
    POST_LOGIN_USER_SUCCESS: "POST_LOGIN_USER_SUCCESS",
    GET_LOGOUT_USER_PENDING: "GET_LOGOUT_USER_PENDING",
    GET_LOGOUT_USER_ERROR: "GET_LOGOUT_USER_ERROR",
    GET_LOGOUT_USER_SUCCESS: "GET_LOGOUT_USER_SUCCESS"
};

export const currentUserActions = {
    GET_CURRENT_USER_PENDING: "GET_CURRENT_USER_PENDING",
    GET_CURRENT_USER_ERROR: "GET_CURRENT_USER_ERROR",
    GET_CURRENT_USER_SUCCESS: "GET_CURRENT_USER_SUCCESS"
};

export const cartActions = {
    ADD_TO_CART_PENDING: "ADD_TO_CART_PENDING",
    ADD_TO_CART_ERROR: "ADD_TO_CART_ERROR",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    UPDATE_CART_PENDING: "UPDATE_CART_PENDING",
    UPDATE_CART_ERROR: "UPDATE_CART_ERROR",
    UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
    GET_CART_PENDING: "GET_CART_PENDING",
    GET_CART_ERROR: "GET_CART_ERROR",
    GET_CART_SUCCESS: "GET_CART_SUCCESS"
};
